config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :event_users
  scope ':type' do
    resources :events, path: '' do
      member do
        get :crop_preview
        post :crop
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  paginates_per 25

  before_save :pre_set_image_url, :normalize_blank_values
  after_save :set_image_url

  self.table_name = 'event'
  self.inheritance_column = 'inheritance'
  validates :image, attachment_presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :email, presence: true
  validates_email_format_of :email
  validates_length_of :name, maximum: 100
  validates_length_of :description, maximum: 120
  validates :start_time, presence: true
  validates :end_time, presence: true, date: { after_or_equal_to: :start_time }

  has_attached_file :image, styles: { cropped: { geometry: '800x>', format: :jpg } }
  crop_attached_file :image, aspect: false
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def prev
    Event.where(type: type).where('start_time < ?', start_time).order(:start_time).last || Event.where(type: type).order(:start_time).last
  end

  def next
    Event.where(type: type).where('start_time > ?', start_time).order(:start_time).first || Event.where(type: type).order(:start_time).first
  end

  def to_s
    "<Event: #{name}>"
  end

  private

  def pre_set_image_url
    self.image_url = 'unknown' unless image_url
  end

  def normalize_blank_values
    self.website = nil unless website.present?
    self.facebook = nil unless facebook.present?
  end

  def set_image_url
    if image.url.start_with?('//')
      update_column(:image_url, "https:#{image.url(:cropped)}")
    else
      update_column(:image_url, image.url(:cropped))
    end
  end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_event_user!, :set_type
  before_action :set_event, only: [:show, :edit, :update, :destroy, :crop_preview, :crop]

  # GET /events
  # GET /events.json
  def index
    @events = if params.key?(:q)
                Event.where(type: @type).where('name LIKE ?', "%#{params[:q]}%").order(:start_time).page params[:page]
              else
                Event.where(type: @type).order(:start_time).page params[:page]
              end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.type = @type

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_path(@type, @event), notice: "#{helpers.event_item} was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_path, notice: "#{helpers.event_item} was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: "#{helpers.event_item} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def crop_preview
  end

  def crop
    @event.image.reprocess!
    @event.save
    format.html { redirect_to event_path, notice: "#{helpers.event_item} was successfully updated." }
    format.json { render :show, status: :ok, location: @event }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_type
    @type = params[:type]
    redirect_to root_path unless @type == 'fling'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description, :image, :start_time, :end_time, :website, :facebook, :email, :image_original_w, :image_original_h, :image_crop_x, :image_crop_y, :image_crop_w, :image_crop_h)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if event_user_signed_in?
      redirect_to events_path('fling')
    else
      redirect_to new_event_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def absolute_url(url)
    /^http/i.match?(url) ? url : "https://#{url}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_name
    case @type
    when 'fling'
      'Fling'
    else
      'Event'
    end
  end

  def event_item
    case @type
    when 'fling'
      'Performer'
    else
      'Item'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, url: event.new_record? ? events_path : event_path, local: true) do |form| %>
<div class="row">
    <div class="col-md-6">
        <% if event.errors.any? %>
            <div class="alert alert-danger">
                <b><%= pluralize(event.errors.count, "error") %> prevented this <%= event_item.downcase %> from being saved:</b>

                <ul>
                    <% event.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, id: :event_name, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, id: :event_description, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= form.label :image %>
            <%= form.file_field :image, id: :event_image, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= form.label :start_time %>
            <div class="form-inline">
                <input type="text" class="form-control mr-1" id="start_time_date" />
                <input type="text" class="form-control" id="start_time_time" />
                <%= form.hidden_field :start_time, id: :event_start_time, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <div id="duration-wrapper">
                <span>Duration</span>
                <div id="quick-buttons">
                    <button class="btn btn-light btn-sm" data-value="900">15 Minutes</button>
                    <button class="btn btn-light btn-sm" data-value="1200">20 Minutes</button>
                    <button class="btn btn-light btn-sm" data-value="1800">30 Minutes</button>
                    <button class="btn btn-light btn-sm" data-value="3600">1 Hour</button>
                    <button class="btn btn-light btn-sm" data-value="5400">90 Minutes</button>
                    <button class="btn btn-light btn-sm" data-value="7200">2 Hours</button>
                    <button class="btn btn-light btn-sm" data-value="10800">3 Hours</button>
                    <button class="btn btn-light btn-sm" data-value="86400">1 Day</button>
                    <button class="btn btn-light btn-sm" data-value="172800">2 Days</button>
                    <button class="btn btn-light btn-sm" data-value="other">Other</button>
                </div>
            </div>
            <div id="end-time-wrapper">
                <%= form.label :end_time %>
                <div class="form-inline">
                    <input type="text" class="form-control mr-1" id="end_time_date" />
                    <input type="text" class="form-control" id="end_time_time" />
                    <%= form.hidden_field :end_time, id: :event_end_time, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, id: :event_email, class: "form-control" %>
            <span class="help-text">We will use this to contact you if there are any issues with the information.</span>
        </div>

        <div class="form-group">
            <%= form.label :website %>
            <%= form.text_field :website, id: :event_website, class: "form-control" %>
            <span class="help-text">A link to a website associated with this event. (Optional)</span>
        </div>

        <div class="form-group">
            <%= form.label :facebook %>
            <%= form.text_field :facebook, id: :event_facebook, class: "form-control" %>
            <span class="help-text">A link to the facebook page associated with this event. (Optional)</span>
        </div>
    </div>
    <div class="col-md-6">
        <b>Preview</b>
        <%= render 'preview' %>
    </div>
</div>
<div class="actions float-left">
    <%= form.submit (form.object.new_record? ? 'Create' : 'Update'), class: 'btn btn-primary' %>
</div>
<% end %>

app/views/events/_preview.html.erb
<div class="phone-preview">
    <div class="marvel-device iphone8 silver">
        <div class="top-bar"></div>
        <div class="sleep"></div>
        <div class="volume"></div>
        <div class="camera"></div>
        <div class="sensor"></div>
        <div class="speaker"></div>
        <div class="screen">
            <%= image_tag 'phone_header.png' %>
            <div class="box">
                <div class="img-wrapper">
                    <% if @event.image.exists? %>
                        <img style="background-image: url(<%= @event.image_url %>)">
                    <% else %>
                        <img />
                    <% end %>
                </div>
                <div class="box-text">
                    <b class="box-title"><%= @event.name.presence or 'Your Title' %></b>
                    <span class="box-desc"><%= @event.description.presence or 'Your Description' %></span>
                    <span class="box-date">Today at <% if @event.start_time %><%= @event.start_time.strftime('%l:%M%P') %><% else %>7:20pm<% end %></span>
                </div>
            </div>
        </div>
        <div class="home"></div>
        <div class="bottom-bar"></div>
    </div>
</div>

app/views/events/crop_preview.html.erb
<h2>Crop <%= event_item %></h2>
<hr />
<%= form_with(model: @event, url: event_path, local: true) do |form| %>
    <div class="form-group">
        <%= form.cropbox :image, box_width: 800 %>
    </div>
    <div class="actions float-left">
        <%= form.submit 'Crop', class: 'btn btn-primary' %>
    </div>
<% end %>
<div class="float-right"><%= link_to 'Cancel', events_path, class: 'btn btn-secondary' %></div>

app/views/events/edit.html.erb
<h2>Editing <%= event_item %></h2>
<hr />
<%= render 'form', event: @event %>

<div class="float-right">
    <%= link_to 'Show', event_path, class: 'btn btn-primary' %>
    <%= link_to 'Cancel', events_path, class: 'btn btn-secondary' %>
</div>

app/views/events/index.html.erb
<h2><%= event_name %> <%= event_item.pluralize %></h2>
<hr />
<table id="events" class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Start time</th>
      <th>End time</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @events.each do |event| %>
      <tr data-link="<%= event_path(@type, event) %>">
        <td><%= event.name %></td>
        <td><img class="event-img" src="<%= event.image_url %>" /></td>
        <td><%= timeago_tag event.start_time, force: true %></td>
        <td><%= timeago_tag event.end_time, force: true %></td>
        <td>
            <%= link_to 'Edit', edit_event_path(@type, event), class: "btn btn-success btn-sm" %>
            <%= link_to 'Delete', event_path(@type, event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
      <% end.empty? %>
      <tr>
        <td colspan="5">You have not added any <%= event_item.pluralize %> yet! Use the button below to add one.</td>
      </tr>
      <% end %>
  </tbody>
</table>

<hr />
<%= paginate @events %>


<%= link_to "New #{event_item}", new_event_path, class: "btn btn-success" %>

app/views/events/new.html.erb
<h2>New <%= event_item %></h2>
<hr />
<%= render 'form', event: @event %>
<div class="float-right"><%= link_to 'Cancel', events_path, class: 'btn btn-secondary' %></div>

app/views/events/show.html.erb
<h2><%= event_item %></h2>
<hr />
<div class="row">
  <div class="col-md-6">
    <p>
      <strong>Name:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Image:</strong> <br />
      <img class="event-img" src="<%= @event.image_url %>">
      <div style="word-wrap: break-word"><b>URL:</b> <%= link_to @event.image_url, @event.image_url %></div>
    </p>

    <p>
      <strong>Start time:</strong>
      <%= @event.start_time.to_formatted_s(:custom_long) %> (<%= timeago_tag @event.start_time, force: true %>)
    </p>

    <p>
      <strong>End time:</strong>
      <%= @event.end_time.to_formatted_s(:custom_long) %> (<%= timeago_tag @event.end_time, force: true %>)
    </p>

    <p>
      <strong>Duration:</strong>
      <%= distance_of_time_in_words(@event.start_time, @event.end_time) %>
    </p>
    <p>
      <b>Contact Information</b>
      <ul>
          <li><b>Email:</b> <%= @event.email %></li>
          <li><b>Website:</b> <%= @event.website ? link_to(@event.website, absolute_url(@event.website)) : 'None' %></li>
          <li><b>Facebook:</b> <%= @event.facebook ? link_to(@event.facebook, absolute_url(@event.facebook)) : 'None' %></li>
      </ul>
    </p>
  </div>
  <div class="col-md-6">
      <div class="float-right">
        <%= link_to '<', event_path(@type, @event.prev), class: "btn btn-light btn-sm" %>
        <%= link_to '>', event_path(@type, @event.next), class: "btn btn-light btn-sm" %>
      </div>
      <b>Preview</b>
      <%= render 'preview' %>
  </div>
</div>
<br />
<div class="actions">
    <%= link_to 'Edit', edit_event_path, class: "btn btn-primary" %>
    <%= link_to 'Crop', crop_preview_event_path, class: "btn btn-warning", data: { turbolinks: false } %>
    <div class="float-right">
        <%= link_to 'Back', events_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= event_name %> Editor</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="content">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <%= yield %>

        <div class="clearfix"></div>

        <hr />
        Made with <svg class="fa-heart" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M414.9 24C361.8 24 312 65.7 288 89.3 264 65.7 214.2 24 161.1 24 70.3 24 16 76.9 16 165.5c0 72.6 66.8 133.3 69.2 135.4l187 180.8c8.8 8.5 22.8 8.5 31.6 0l186.7-180.2c2.7-2.7 69.5-63.5 69.5-136C560 76.9 505.7 24 414.9 24z"></path></svg> by <a href="https://pennlabs.org">Penn Labs</a>
        <% if event_user_signed_in? %>
            <span class="float-right"><%= link_to 'Logout', destroy_event_user_session_path, method: :delete %></span>
        <% end %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Event Editor</h1>